package config

const APP_VERSION = "1.0.1"
const SERVER_PORT = "9111"

var (
	MISTRAL_TOKEN = Env("MISTRAL_TOKEN")
	MISTRAL_AGENT = Env("MISTRAL_AGENT")
	DB_CONNECTION = Env("DB_CONNECTION")
	BEARER_TOKEN  = Env("BEARER_TOKEN")
)
