package config

const APP_VERSION = "dev"
const SERVER_PORT = "9111"

var (
	MISTRAL_TOKEN = Env("MISTRAL_TOKEN")
	MISTRAL_AGENT = Env("MISTRAL_AGENT")
	DB_CONNECTION = Env("DB_CONNECTION")
	BEARER_TOKEN  = Env("BEARER_TOKEN")
	RATE_LIMIT    = EnvAsInt("RATE_LIMIT", 5)
)
