package config

var APP_VERSION = "dev"

var (
	MISTRAL_TOKEN     = Env("MISTRAL_TOKEN")
	BEARER_TOKEN      = Env("BEARER_TOKEN")
	RATE_LIMIT        = EnvAsInt("RATE_LIMIT", 5)
	OPENROUTER_TOKEN  = Env("OPENROUTER_TOKEN")
	OPENAI_TOKEN      = Env("OPENAI_TOKEN")
	POSTGRES_HOST     = Env("POSTGRES_HOST")
	POSTGRES_PORT     = Env("POSTGRES_PORT")
	POSTGRES_USER     = Env("POSTGRES_USER")
	POSTGRES_PASSWORD = Env("POSTGRES_PASSWORD")
	POSTGRES_DB       = Env("POSTGRES_DB")
	SERVER_PORT       = Env("SERVER_PORT")
)
